language: python
python: 
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"     
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
branches:
  - master
notifications:
  email:
    recipients:
      - dpumar3@gmail.com
install:
  - pip install numpy as np
script:
  - pytest

